print('False: ' + str(bool(False)))
print('"" :' + str(bool("")))
print('0 : ' + str(bool(0)))
print('[] : ' + str(bool([])))
print('None :' + str(bool(None)))
print()
print('"Anything" :' + str(bool("Anything")))
print('"False" :' + str(bool("False")))
print('1 :' + str(bool(1)))
print('-33 :' + str(bool(-33)))
print('9 :' + str(bool(9)))